image: hub.dianchu.cc/library/base-node:1.0.1

variables:
  DOCKER_DRIVER: overlay
  DC_REGISTRY: hub.dianchu.cc
  DC_REGISTRY_USER: gitlab_ci
  DC_REGISTRY_PASS: Gitlab_c1
  FRONT_NAME: dc-borrow-platform-front
  BUILD_TAG: 0.1.9

stages:
  - build_file
  # - server_deploy

build_file:
  stage: build_file
  only:
    - ci
  script:
    # - export BUILD_TAG=$(cat version)
    - cnpm install
    - npm run build
    - docker login -u $DC_REGISTRY_USER -p $DC_REGISTRY_PASS $DC_REGISTRY
    - echo $DC_REGISTRY/library/$FRONT_NAME:$BUILD_TAG
    - docker build -t $DC_REGISTRY/library/$FRONT_NAME:$BUILD_TAG .
    - docker push $DC_REGISTRY/library/$FRONT_NAME:$BUILD_TAG
    - docker tag $DC_REGISTRY/library/$FRONT_NAME:$BUILD_TAG $DC_REGISTRY/library/$FRONT_NAME:latest
    - docker push $DC_REGISTRY/library/$FRONT_NAME:latest
  cache:
    paths:
      - node_modules/
  tags:
    - rancher_docker

# server_deploy:
#   stage: server_deploy
#   only:
#     - ci
#   script:
#     - apk add curl --no-cache
#     - IMAGE=$DC_REGISTRY/library/$FRONT_NAME
#     - TAG=latest
#     - "curl -X POST 'http://192.168.5.84:8080/v1-webhooks/endpoint?key=5jIQMq9gTnuuEKOLRYHfGZZQF9weqiqSaGZA8O4R&projectId=1a785' -H 'content-type: application/json' -d '{\"push_data\": {\"tag\": \"'\"${TAG}\"'\"},\"repository\": {\"repo_name\": \"'\"${IMAGE}\"'\"}}'"
#   tags:
#     - rancher_docker
